namespace: #namespace#
api:
  name: &api-name document-management-api
  port: &api-port 9984
tlsDeployment: true

###################################
# Kubernetes - image
###################################
replicaCount: 1
image:
  registry_hostname: &registry-host nexus.oddo-bhf.com
  registry_port: &registry-port 8443
  tag: &image-tag 1.0.0-SNAPSHOT
  pullPolicy: Always
  useImagePullSecrets: false
  imagePullSecrets: imagePullSecrets
###################################

spring:
  setActiveProfile: false
  activeProfile: &spring-activeProfile kube

db:
  host: ged-db-rw.ged-lab.svc.cluster.local
  port: 5432
  name: dms-db
  user: app
  password: W6nqBPtQenRTNMXBusE9V29vVtufW0ZsxqT4PknoaWH9z2BFDAn79RGRXFfnvEjK

storage:
  type: &storage-type local
  basePath: &local-root-folder /var/data/ged

###################################
# Kubernetes - NodePort Configs
###################################
service:
  type: ClusterIP
  port: 80
###################################
# Kubernetes - Ingress Configs
###################################
ingress:
  ## annotations for the copernic-backend-pod Ingress
  ##
  annotations:
    # kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "16"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "256k"
    nginx.ingress.kubernetes.io/proxy-max-temp-file-size: "2048m"
    nginx.ingress.kubernetes.io/proxy-body-size: "1024m"
    nginx.org/client-max-body-size: "1024m"
    # rest of nginx config #
  labels: {}


deploy:
  ## For creating a Route, allowing your application to be accessed from outside the OCP cluster
  route:
    enabled: true
    ## More information: https://docs.openshift.com/container-platform/4.6/networking/routes/secured-routes.html
    tls:
      enabled: true
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
      ## IMPORTANT: Do not check 'key' into git!
      key:
      caCertificate:
      certificate:
      destinationCACertificate:

persistence:
  usePersistentVolume: true
  pvName: #pv_name#
  pvcName: ged-volume-pvc
