apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      {{- if .Values.image.useImagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.image.imagePullSecrets }}
      {{- end }}
      containers:
      - name : {{ .Values.api.name }}
        image: "{{ .Values.image.registry_hostname }}:{{ .Values.image.registry_port }}/snapshots/{{.Values.api.name}}:{{.Values.image.tag}}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          {{- if .Values.spring.setActiveProfile }}
          - name: SPRING_PROFILES_ACTIVE
            value: {{ .Values.spring.activeProfile }}
          {{- end}}
          - name: DB_HOST
            value: {{ .Values.db.host }}
          - name: DB_PORT
            value: "{{ .Values.db.port }}"
          - name: DB_NAME
            value: {{ .Values.db.name }}
          - name: DB_USER
            value: {{ .Values.db.user }}
          - name: DB_PASSWORD
            value: {{ .Values.db.password }}
          - name: JAVA_TOOL_OPTIONS
            value: "-Dserver.port={{ .Values.api.port}} -Dserver.address=0.0.0.0 -Dstorage.type={{.Values.storage.type}} -Dstorage.local.basePath={{.Values.storage.basePath}}"
        ports:
          - containerPort: {{ .Values.api.port }}
        {{- if .Values.persistence.usePersistentVolume }}
        volumeMounts:
          - mountPath: {{ .Values.storage.basePath }}
            name: {{ .Values.persistence.pvName }}
      volumes:
        - name: {{ .Values.persistence.pvName }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.pvcName }}
        {{- end }}