{{- if not (.Values.deploy.route.enabled) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  annotations:
  {{- toYaml .Values.ingress.annotations | nindent 4 }}
  labels:
    component: {{ .Chart.Name }}
spec:
  ingressClassName: public
  rules:
    - http:
        paths:
          - backend:
              service:
                name: {{ .Values.api.name }}
                port:
                  number: {{ .Values.service.port }}
            path: /{{ .Values.namespace }}(/|$)(.*)
            pathType: "Prefix"
{{- end }}