apiVersion: v1
kind: Service
metadata :
  name : {{ .Values.api.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      name: {{ .Values.api.name }}-port
      targetPort: {{ .Values.api.port }}
