name: Build UI

on:
  push:
    branches: [ "develop" ]
    paths:
      - 'document-management-web/**'


jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Build and push the image
        working-directory: ./document-management-web
        run : |
          npm install
          npm run build
          docker login --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} ghcr.io
          docker build -t ghcr.io/openfilz/document-management-web:latest . 
          docker push ghcr.io/openfilz/document-management-web:latest