name: Create Release

on:
  push:
    branches:
      - main

jobs:
  build:
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo The PR was merged to main....

      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven

      - name: Configure Git user
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com'

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          passphrase: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}

      - name: Setup Maven settings.xml
        uses: s4u/maven-settings-action@v3.1.0
        with:
          servers: |
            [{
                "id": "central",
                "username": "${{ secrets.MAVEN_USERNAME }}",
                "password": "${{ secrets.MAVEN_PASSWORD }}"
            }]

      - name: Extract Maven project version
        run: echo "version=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT
        id: project

      - name: Remove SNAPSHOT from version
        uses: spassai/get-between-action@v1
        id: version
        with:
          string: ${{ steps.project.outputs.version }}"
          start: ''
          end: '-SNAPSHOT'

      - name: Prepare Release
        run: mvn -B release:prepare -DtagNameFormat=v@{project.version} -Darguments="-DskipTests -Dgpg.skip"

      - name: Perform Release
        run: mvn -B release:perform -Darguments="-Pkube -Dregistry.hostname=ghcr.io -Dregistry.port=443 -Ddocker.context.path=openfilz/ -Djib.to.auth.username=${{ github.actor }} -Djib.to.auth.password=${{ secrets.GITHUB_TOKEN }}"

      - name: Generate Changelog
        run: mvn git-changelog-maven-plugin:git-changelog

      - name: Commit Changelog
        run: |
          git add CHANGELOG.md
          git commit -m "docs: update changelog for version ${{ steps.version.outputs.substring }}"
          git push origin main

      - name: Get Changelog Entry
        id: changelog
        run: |
          CHANGELOG_ENTRY=$(sed -n "/## ${GITHUB_REF#refs/tags/}/,/## /p" CHANGELOG.md | sed '$d')
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG_ENTRY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.substring }}
          name: Release v${{ steps.version.outputs.substring }}
          body: ${{ steps.changelog.outputs.changelog }}
          fail_on_unmatched_files: false
          files: |
            document-management-api/target/*${{ steps.version.outputs.substring }}.jar
            document-management-gateway/target/*${{ steps.version.outputs.substring }}.jar
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge main -> develop
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: develop
          github_token: ${{ secrets.GITHUB_TOKEN }}
